# Escalamiento de Datos

In [ ]:
## data:https://www.kaggle.com/competitions/playground-series-s5e12/data?select=train.csv

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df_train=pd.read_csv("/content/drive/MyDrive/You tube canal /Preprocesamiento de datos /Variables numericas/train.csv")
df_test=pd.read_csv("/content/drive/MyDrive/You tube canal /Preprocesamiento de datos /Variables numericas/test.csv")

In [ ]:
df_train.head()

,id,age,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,sleep_hours_per_day,screen_time_hours_per_day,bmi,waist_to_hip_ratio,systolic_bp,...,gender,ethnicity,education_level,income_level,smoking_status,employment_status,family_history_diabetes,hypertension_history,cardiovascular_history,diagnosed_diabetes
0,0,31,1,45,7.7,6.8,6.1,33.4,0.93,112,...,Female,Hispanic,Highschool,Lower-Middle,Current,Employed,0,0,0,1.0
1,1,50,2,73,5.7,6.5,5.8,23.8,0.83,120,...,Female,White,Highschool,Upper-Middle,Never,Employed,0,0,0,1.0
2,2,32,3,158,8.5,7.4,9.1,24.1,0.83,95,...,Male,Hispanic,Highschool,Lower-Middle,Never,Retired,0,0,0,0.0
3,3,54,3,77,4.6,7.0,9.2,26.6,0.83,121,...,Female,White,Highschool,Lower-Middle,Current,Employed,0,1,0,1.0
4,4,54,1,55,5.7,6.2,5.1,28.8,0.90,108,...,Male,White,Highschool,Upper-Middle,Never,Retired,0,1,0,1.0


In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700000 entries, 0 to 699999
Data columns (total 26 columns):
 #   Column                              Non-Null Count   Dtype  
---  ------                              --------------   -----  
 0   id                                  700000 non-null  int64  
 1   age                                 700000 non-null  int64  
 2   alcohol_consumption_per_week        700000 non-null  int64  
 3   physical_activity_minutes_per_week  700000 non-null  int64  
 4   diet_score                          700000 non-null  float64
 5   sleep_hours_per_day                 700000 non-null  float64
 6   screen_time_hours_per_day           700000 non-null  float64
 7   bmi                                 700000 non-null  float64
 8   waist_to_hip_ratio                  700000 non-null  float64
 9   systolic_bp                         700000 non-null  int64  
 10  diastolic_bp                        700000 non-null  int64  
 11  heart_rate                

In [ ]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler,RobustScaler, MaxAbsScaler,OneHotEncoder

In [ ]:
feat_binary=['family_history_diabetes',
 'hypertension_history',
 'cardiovascular_history']
target="diagnosed_diabetes"

In [ ]:
feat_cuant=df_train.select_dtypes(exclude="object").drop(feat_binary+["id",target],axis=1).columns
feat_cuant=list(feat_cuant)
feat_cuant

['age',
 'alcohol_consumption_per_week',
 'physical_activity_minutes_per_week',
 'diet_score',
 'sleep_hours_per_day',
 'screen_time_hours_per_day',
 'bmi',
 'waist_to_hip_ratio',
 'systolic_bp',
 'diastolic_bp',
 'heart_rate',
 'cholesterol_total',
 'hdl_cholesterol',
 'ldl_cholesterol',
 'triglycerides']

In [ ]:
len(feat_cuant)

15

In [ ]:
feat_cual=df_train.select_dtypes(include="object").columns
feat_cual=list(feat_cual)
feat_cual

['gender',
 'ethnicity',
 'education_level',
 'income_level',
 'smoking_status',
 'employment_status']

## Metodos de escalamiento de datos

####StandardScaler

In [ ]:
scal_std=StandardScaler()
scal_std_tr=scal_std.fit_transform(df_train[feat_cuant])
scal_std_tr

array([[-1.6609939 , -1.02310918, -0.68816837, ...,  0.50526412,
         0.58321476, -0.8521576 ],
       [-0.03086388, -0.06908244, -0.14124032, ..., -0.46249272,
         0.95120193,  0.0371129 ],
       [-1.57519758,  0.8849443 ,  1.51907697, ...,  0.62623372,
         0.58321476, -0.60962928],
       ...,
       [-1.31780863, -1.02310918, -0.59050264, ...,  0.62623372,
        -1.36186029,  1.73481112],
       [-0.11666019, -0.06908244, -0.19983975, ...,  0.1423553 ,
         0.26779718,  0.40090537],
       [-0.71723441,  1.83897104, -0.47330378, ...,  1.11011215,
         0.11008839,  1.45186141]])

Distribución centrada y escalada según desviación estándar

In [ ]:
scal_std_tr.mean(axis=0)

array([-2.90591678e-16, -1.97261889e-16, -9.84203195e-17,  5.32704040e-16,
        2.06609587e-15,  9.30871888e-16, -1.53668062e-15,  4.54625544e-16,
       -3.03452501e-16, -4.10287677e-16, -5.32460425e-16,  5.79736893e-16,
       -4.83422826e-17,  9.44818826e-17, -1.17990697e-16])

In [ ]:
scal_std_tr.var(axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

####MinMaxScaler

In [ ]:
scal_minmax=MinMaxScaler()
scal_minmax_tr=scal_minmax.fit_transform(df_train[feat_cuant])
scal_minmax_tr

array([[0.17142857, 0.        , 0.05898123, ..., 0.53623188, 0.40909091,
        0.27413127],
       [0.44285714, 0.125     , 0.09651475, ..., 0.42028986, 0.45454545,
        0.35907336],
       [0.18571429, 0.25      , 0.21045576, ..., 0.55072464, 0.40909091,
        0.2972973 ],
       ...,
       [0.22857143, 0.        , 0.06568365, ..., 0.55072464, 0.16883117,
        0.52123552],
       [0.42857143, 0.125     , 0.0924933 , ..., 0.49275362, 0.37012987,
        0.39382239],
       [0.32857143, 0.375     , 0.07372654, ..., 0.60869565, 0.35064935,
        0.49420849]])

In [ ]:
scal_minmax_tr.min(axis=0)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
scal_minmax_tr.max(axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

####RobustScaler

In [ ]:
scal_robus=RobustScaler()
scal_robus_tr=scal_robus.fit_transform(df_train[feat_cuant])
scal_robus_tr

array([[-1.1875    , -0.5       , -0.55319149, ...,  0.36363636,
         0.40740741, -0.63636364],
       [ 0.        ,  0.        ,  0.04255319, ..., -0.36363636,
         0.66666667,  0.03030303],
       [-1.125     ,  0.5       ,  1.85106383, ...,  0.45454545,
         0.40740741, -0.45454545],
       ...,
       [-0.9375    , -0.5       , -0.44680851, ...,  0.45454545,
        -0.96296296,  1.3030303 ],
       [-0.0625    ,  0.        , -0.0212766 , ...,  0.09090909,
         0.18518519,  0.3030303 ],
       [-0.5       ,  1.        , -0.31914894, ...,  0.81818182,
         0.07407407,  1.09090909]])

Su propiedad central:

In [ ]:
np.median(scal_robus_tr,axis=0)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.quantile(scal_robus_tr,axis=0,q=0.75)-np.quantile(scal_robus_tr,axis=0,q=0.25)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

####MaxAbsScaler

In [ ]:
scal_maxabs=MaxAbsScaler()
scal_maxabs_tr=scal_maxabs.fit_transform(df_train[feat_cuant])
scal_maxabs_tr

array([[0.34831461, 0.11111111, 0.06024096, ..., 0.64444444, 0.55609756,
        0.35172414],
       [0.56179775, 0.22222222, 0.09772423, ..., 0.55555556, 0.5902439 ,
        0.42758621],
       [0.35955056, 0.33333333, 0.21151272, ..., 0.65555556, 0.55609756,
        0.37241379],
       ...,
       [0.39325843, 0.11111111, 0.0669344 , ..., 0.65555556, 0.37560976,
        0.57241379],
       [0.5505618 , 0.22222222, 0.09370817, ..., 0.61111111, 0.52682927,
        0.45862069],
       [0.47191011, 0.44444444, 0.07496653, ..., 0.7       , 0.51219512,
        0.54827586]])

In [ ]:
scal_maxabs_tr.max(axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
scal_maxabs_tr.min(axis=0)

array([0.21348315, 0.11111111, 0.00133869, 0.01010101, 0.31313131,
       0.03636364, 0.39322917, 0.64761905, 0.55828221, 0.49038462,
       0.41584158, 0.40484429, 0.23333333, 0.24878049, 0.10689655])

## Modelo de Machine Learning

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,roc_auc_score

In [ ]:
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.compose import ColumnTransformer


In [ ]:
x_train,x_test,y_train,y_test=train_test_split(df_train.drop(["id","diagnosed_diabetes"],axis=1),
                                               df_train["diagnosed_diabetes"],test_size=0.2,random_state=2026)

In [ ]:
preprocessor = ColumnTransformer(
    transformers=[
        ('trans_num', StandardScaler(), feat_cuant),
      ('one_hot',OneHotEncoder(handle_unknown='ignore',sparse_output=False),feat_cual)
    ],remainder="passthrough", verbose_feature_names_out=False).set_output(transform="pandas")

In [ ]:
prepro_arr=preprocessor.fit_transform(x_train)

In [ ]:
prepro_arr.shape

(560000, 42)

In [ ]:
from sklearn.linear_model import SGDClassifier

In [ ]:
model0 = Pipeline(steps=[('preprocessor', preprocessor),
      ('model',SGDClassifier(loss="log_loss",max_iter=1000,random_state=123))])

In [ ]:
model0.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning: 
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(


Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trans_num', MaxAbsScaler(),
                                                  ['age',
                                                   'alcohol_consumption_per_week',
                                                   'physical_activity_minutes_per_week',
                                                   'diet_score',
                                                   'sleep_hours_per_day',
                                                   'screen_time_hours_per_day',
                                                   'bmi', 'waist_to_hip_ratio',
                                                   'systolic_bp',
                                                   'diastolic_bp', 'heart_rate',
                                                   'cholesterol_total',
                                                   'hdl_cholesterol',
                                                   'ldl_cholesterol',
                                                   'triglycerides']),
                                                 ('one_hot',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['gender', 'ethnicity',
                                                   'education_level',
                                                   'income_level',
                                                   'smoking_status',
                                                   'employment_status'])])),
                ('model', SGDClassifier(loss='log_loss', random_state=123))])

In [ ]:
pred_test=model0.predict_proba(x_test)[:,1]

In [ ]:
print(classification_report(y_test,pred_test>0.5))

              precision    recall  f1-score   support

         0.0       0.62      0.26      0.36     52731
         1.0       0.67      0.90      0.77     87269

    accuracy                           0.66    140000
   macro avg       0.64      0.58      0.57    140000
weighted avg       0.65      0.66      0.62    140000



In [ ]:
roc_auc_score(y_test,pred_test)

np.float64(0.6917332122025097)

In [ ]:
list_metodo=[StandardScaler(),MinMaxScaler(),RobustScaler(),MaxAbsScaler()]

In [ ]:
for i in list_metodo:
  preprocessor = ColumnTransformer(
  transformers=[
          ('trans_num', i, feat_cuant),
        ('one_hot',OneHotEncoder(handle_unknown='ignore',sparse_output=False),feat_cual)
      ],remainder="passthrough")

  model0 = Pipeline(steps=[('preprocessor', preprocessor),
        ('model',SGDClassifier(loss="log_loss",max_iter=1000,random_state=123))
          ])
  model0.fit(x_train,y_train)

  pred_test=model0.predict_proba(x_test)[:,1]

  print("Metodo",i)
  print("Ttest: Metrica AUC",roc_auc_score(y_test,pred_test))

Metodo StandardScaler()
Ttest: Metrica AUC 0.6912734630953227
Metodo MinMaxScaler()
Ttest: Metrica AUC 0.6917340355792576
Metodo RobustScaler()
Ttest: Metrica AUC 0.6906320384838234
Metodo MaxAbsScaler()
Ttest: Metrica AUC 0.6917332122025097


### Interacciones y PCA(componentes principales)

In [ ]:
from sklearn.decomposition import PCA

In [ ]:
from sklearn.preprocessing import PolynomialFeatures

#### 🔹 degree = 2
Para $X_1,\; X_2$

Agrega términos cuadráticos e interacciones:

$
X_1,\; X_2,\; X_1^2,\; X_2^2,\; X_1X_2
$



In [ ]:
trans_num=Pipeline(steps=[
     ("poly",PolynomialFeatures(degree=2,interaction_only=True,
        include_bias=False)),#degree=grado máximo del polinomio
     ("scaler_robust",MinMaxScaler()),
     ("PCA",PCA(n_components=0.95,random_state=123)),
     ])
preprocessor = ColumnTransformer(
transformers=[
          ('trans_num', trans_num, feat_cuant),
        ('one_hot',OneHotEncoder(handle_unknown='ignore',sparse_output=False),feat_cual)
      ],remainder="passthrough")

model0 = Pipeline(steps=[
          ('preprocessor', preprocessor),
        ('model',SGDClassifier(loss="log_loss",max_iter=1000,random_state=123))])#LogisticRegression(solver="saga",max_iter=500))])
model0.fit(x_train,y_train)

pred_test=model0.predict_proba(x_test)[:,1]

print("Ttest: Metrica AUC",roc_auc_score(y_test,pred_test))

Ttest: Metrica AUC 0.6927682389320777


### Con datos no escalados normalmente:

🔹 Tarda más en converger

🔹 Puede necesitar más iteraciones

🔹 Puede volverse inestable

🔹 Incluso puede no converger bien

In [ ]:
%%time
preprocessor = ColumnTransformer(
transformers=[
        ('one_hot',OneHotEncoder(handle_unknown='ignore',sparse_output=False),feat_cual)
      ],remainder="passthrough")

model0 = Pipeline(steps=[
          ('preprocessor', preprocessor),
        ('model',SGDClassifier(loss="log_loss",max_iter=1000,random_state=123))])#LogisticRegression(solver="saga",max_iter=500))])

model0.fit(x_train,y_train)

pred_test=model0.predict_proba(x_test)[:,1]

CPU times: user 2min 17s, sys: 596 ms, total: 2min 17s
Wall time: 2min 52s


In [ ]:
print("Ttest: Metrica AUC",roc_auc_score(y_test,pred_test))

Ttest: Metrica AUC 0.6883681288033406


In [ ]:
pred_test=model0.predict_proba(df_test[x_train.columns])[:,1]

In [ ]:
sub={
    "id":df_test["id"],
    "diagnosed_diabetes":pred_test
}

In [ ]:
df_sub=pd.DataFrame(sub)

In [ ]:
df_sub.to_csv("submision_v1.csv",index=None,header=True)